version: 0.1
phase:
  install:
    commands:
      - aws cloudformation package --template-file adobe-test/template.yaml --s3-bucket ncode-zip-files --output-template-file output_template.yaml --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
artifacts:
  type: zip
  files:
    - template.yaml
    - output_template.yaml