version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "I am in buildspec"
      - pwd
      - echo $(ls-la)
      - chmod +x ./bin/deploy.sh
      - ./deploy.sh
