version: 0.1
phase:
  install:
    commands:
      - aws cloudformation package --template-file adobe-test/samTemplate.yaml --s3-bucket nproject-code-artifacts --output-template-file outputSamtemplate.yaml --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml