version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "This buildspec.yaml"
      - pwd
      - aws cloudformation package --template-file template.yaml --s3-bucket ncode-zip-files --output-template-file output_template.yaml
      - echo "done"

artifacts:
  type: zip
  files:
    - template.yaml
    - output_template.yaml