version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "This buildspec.yaml"
      - pwd
      - pip install -r requirements.txt
      - aws cloudformation package --template-file my-sam-app/template.yaml --s3-bucket ncode-zip-files --output-template-file output_template.yaml
      - echo "done"
artifacts:
  type: zip
  files:
    - template.yaml
    - output_template.yaml