AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Resources:

  processrevenuefunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: "python3.7"
      Role: arn:aws:iam::694992456702:role/mylambda-execute-s3-file
      Handler: lambda_function.lambda_handler
      Timeout: 120
      FucntionName: process-revenue
      CodeUri: ../lambdas/lambda_code/
      Description: Lambda Function to process tsv file
